---
name: silverguacho
# description will be included in the image's metadata
description: SilverGuacho Image

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42
# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: common/common.yml
  - from-file: common/virt-modules.yml
  - from-file: common/os-release.yml
